[versions]
agp = "8.13.2"
kotlin = "2.3.0"
android-minSdk = "24"
android-compileSdk = "36"
vanniktechMavenPublish = "0.35.0"

# Compose
compose-multiplatform = "1.9.3"

# CameraX
androidx-camerax = "1.5.2"
androidx-lifecycle = "2.10.0"
androidx-activity = "1.12.2"

# Coroutines
coroutines = "1.10.2"

# KMP-NativeCoroutines
kmpNativeCoroutines = "1.0.0"

# Spotless
spotless = "6.25.0"

# Binary Compatibility Validator
binaryCompatibilityValidator = "0.17.0"

# KSP
ksp = "2.3.4"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# KMP-NativeCoroutines
kmp-nativecoroutines-core = { module = "com.rickclephas.kmp:kmp-nativecoroutines-core", version.ref = "kmpNativeCoroutines" }
kmp-nativecoroutines-annotations = { module = "com.rickclephas.kmp:kmp-nativecoroutines-annotations", version.ref = "kmpNativeCoroutines" }

# CameraX
camerax-core = { module = "androidx.camera:camera-core", version.ref = "androidx-camerax" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camerax" }
camerax-video = { module = "androidx.camera:camera-video", version.ref = "androidx-camerax" }
camerax-compose = { module = "androidx.camera:camera-compose", version.ref = "androidx-camerax" }

# AndroidX
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kmpNativeCoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmpNativeCoroutines" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }