name: Publish
on:
  workflow_dispatch:
    inputs:
      publish_core:
        description: 'Publish Core Module'
        required: false
        type: boolean
        default: false
      publish_compose:
        description: 'Publish Compose Module'
        required: false
        type: boolean
        default: false
      publish_mlkit_barcode:
        description: 'Publish MLKit Barcode Plugin'
        required: false
        type: boolean
        default: false
      publish_mlkit_text:
        description: 'Publish MLKit Text Plugin'
        required: false
        type: boolean
        default: false
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Publish to MavenCentral
        run: |
          if [ "${{ inputs.publish_core }}" != "true" ] && \
             [ "${{ inputs.publish_compose }}" != "true" ] && \
             [ "${{ inputs.publish_mlkit_barcode }}" != "true" ] && \
             [ "${{ inputs.publish_mlkit_text }}" != "true" ]; then
            echo "Error: No modules selected for publication."
            exit 1
          fi

          if [ "${{ inputs.publish_core }}" == "true" ]; then
            echo "Publishing Core Module..."
            ./gradlew :library:core:publishToMavenCentral --no-configuration-cache
          fi
          
          if [ "${{ inputs.publish_compose }}" == "true" ]; then
            echo "Publishing Compose Module..."
            ./gradlew :library:compose:publishToMavenCentral --no-configuration-cache
          fi
          
          if [ "${{ inputs.publish_mlkit_barcode }}" == "true" ]; then
            echo "Publishing MLKit Barcode Plugin..."
            ./gradlew :plugin:mlkit-barcode:publishToMavenCentral --no-configuration-cache
          fi
          
          if [ "${{ inputs.publish_mlkit_text }}" == "true" ]; then
            echo "Publishing MLKit Text Plugin..."
            ./gradlew :plugin:mlkit-text:publishToMavenCentral --no-configuration-cache
          fi
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
